import json
import logging

from spacy import displacy

from flask_app.nlu_pkg.services.sensor_parsing.text_parser import TextParser
from flask_app.nlu_pkg.services.utils.dependency_containers import Application
from flask_app.services.json.custom_encoder import CustomEncoder

# TODO: initiate range stuff on startup, instead on the first range parse request
# TODO: lowercase sentence at the start, preprocess it?
# TODO: handle unable to parse string x to a valid number, instead of just throwing it


container = Application()
text_parser: TextParser = container.services.text_parser()

short_single = [
    "The piano has 88 keys.",
    "The garden fence is 6 feet tall.",
    "The textbook weighs 3 pounds.",
    "The backpack's zipper is 20 centimeters long.",
    "The conference room has a seating capacity of 50.",
    "The car's fuel tank capacity is 15 gallons.",
    "The desktop computer has 16 gigabytes of RAM.",
    "The kitchen counter is 3 feet high.",
    "The recipe calls for 1 teaspoon of salt.",
    "The office desk is 120 centimeters wide.",
    "The smartphone's battery capacity is 3000 milliampere-hours.",
    "The painting is 30 inches by 40 inches.",
    "The microwave's cooking time is 2 minutes.",
    "The bicycle's wheel diameter is 27 inches.",
    "The meeting room temperature is set at 22 degrees Celsius.",
    "The living room rug is 8 feet by 10 feet.",
    "The elevator can carry a maximum load of 1000 kilograms.",
    "The wristwatch's diameter is 42 millimeters.",
    "The garden hose nozzle has a spray radius of 10 feet.",
    "The coffee table is 18 inches in height.",
    "The car's turning radius is 5 meters.",
    "The classroom has 30 desks.",
    "The hiking trail is 3 miles long.",
    "The flashlight's brightness is 200 lumens.",
    "The pizza's diameter is 16 inches.",
    "The swimming pool's depth is 8 feet.",
    "The digital camera has a shutter speed of 1/1000 seconds.",
    "The refrigerator's freezer temperature is -18 degrees Celsius.",
    "The laptop battery life is 8 hours.",
    "The digital scale measures in increments of 0.5 grams.",
    "The bookshelf has 5 shelves.",
    "The car's weight is 2000 kilograms.",
    "The flight duration is 4 hours.",
    "The study desk's width is 120 centimeters.",
    "The skateboard's length is 31 inches.",
    "The dining table can seat 6 people.",
    "The blender's maximum speed is 10,000 revolutions per minute.",
    "The library has 20,000 books.",
    "The coffee maker brews 6 cups at a time.",
    "The camera lens focal length is 50 millimeters.",
    "The tennis court is 78 feet long.",
    "The alarm clock's snooze duration is 9 minutes.",
    "The laptop's weight is 2.3 kilograms.",
    "The painting brushstroke is 2 centimeters wide.",
    "The refrigerator's energy consumption is 150 kilowatt-hours per month.",
    "The fitness tracker's step goal is 10,000 steps.",
    "The window blinds are 36 inches wide.",
    "The water bottle capacity is 500 milliliters."
]

short_range = [
    "The room temperature is above 20 but below 25 degrees Celsius.",
    "The car's speed ranges from 60 to 80 miles per hour.",
    "The backpack's capacity is greater than 20 liters.",
    "The smartphone's battery life spans between 10 and 12 hours.",
    "The oven temperature can be set anywhere from 200 to 450 degrees Fahrenheit.",
    "The television screen size starts at 40 inches and goes beyond.",
    "The fitness tracker monitors heart rate within a range above 60 and beneath 160 beats per minute.",
    "The car's fuel efficiency is in the range of 25 to 30 miles per gallon.",
    "The digital camera's ISO sensitivity covers a spectrum from 100 to 1600.",
    "The hiking trail spans a distance of 5 to 10 miles.",
    "The refrigerator's temperature can be adjusted between 1 and 8 degrees Celsius.",
    "The laptop's screen resolution is above 1080p.",
    "The printer's printing speed is in the range of 20 to 30 pages per minute.",
    "The guitar's price falls within the range of $500 to just below $1000.",
    "The coffee maker's brewing time is between 3 and 5 minutes.",
    "The microwave's power output spans from 800 to 1200 watts.",
    "The washing machine's spin speed ranges from 800 to 1200 revolutions per minute.",
    "The bicycle's gears range from 1 to 21.",
    "The car's weight is between 1500 and over 2000 kilograms.",
    "The smartphone's camera has a zoom capability ranging from 2x to 5x.",
    "The conference room can accommodate anywhere from 30 to just below 50 people.",
    "The laptop's storage capacity is above 256 gigabytes.",
    "The smart thermostat's temperature control spans from just above 15 to below 30 degrees Celsius.",
    "The flashlight has an adjustable brightness level ranging from just above 50 to 200 lumens.",
    "The swimming pool's depth ranges from just above 5 to below 10 feet.",
    "The digital scale can measure weights between 1 and just below 5 kilograms.",
    "The coffee mug holds a volume between 8 and just below 12 ounces.",
    "The kitchen timer can be set for durations between 1 and just below 60 minutes.",
    "The car's turning radius is in the range of just above 4 to below 6 meters.",
    "The desk chair's height is adjustable from just above 40 to below 50 inches.",
    "The electric kettle can heat water between 150 and just below 212 degrees Fahrenheit.",
    "The drone's flight time is between 15 and just below 20 minutes.",
    "The blender has multiple speed settings ranging from just above 1 to 5.",
    "The watch's water resistance is suitable for depths between just above 30 and below 50 meters.",
    "The bookshelf has adjustable shelves that can be spaced from just above 8 to below 12 inches apart.",
    "The thermostat has a programmable temperature range from just above 18 to below 28 degrees Celsius.",
    "The vacuum cleaner's noise level is between 60 and just below 70 decibels.",
    "The bicycle's seat height is adjustable from just above 30 to below 40 inches.",
    "The smartwatch's battery life ranges from just above 2 to below 5 days.",
    "The camera's aperture can be adjusted between just above f/2.8 and below f/16.",
    "The computer monitor's refresh rate is between 60 and just below 144 hertz.",
    "The hiking boots' price falls within the range of just above $80 to below $120.",
    "The oven's timer can be set for durations between 1 and just below 120 minutes.",
    "The sound system's frequency response is in the range of just above 40Hz to below 220kHz.",
    "The alarm clock's volume is adjustable from just above 30 to below 60 decibels.",
    "The tablet's screen size is between 7 and just below 12 inches.",
    "The skateboard's length ranges from just above 28 to below 34 inches.",
    "The refrigerator's energy consumption is between 100 and just below 200 kilowatt-hours per month.",
    "The drone's maximum altitude is in the range of just above 100 to below 500 feet.",
    "The coffee grinder has grind settings from just above fine to below coarse."
]

long_range = [
    "Temperature within the room varies extensively, reaching above a comfortable 20 degrees Celsius but maintaining a threshold below the warmth of 25 degrees Celsius, providing a dynamic and adaptable thermal environment.",
    "The car's speed capabilities span a considerable range, allowing for a driving experience that can be leisurely at 60 miles per hour or swift at 80 miles per hour, catering to diverse preferences and road conditions.",
    "The backpack provides ample space for storage, accommodating the diverse needs of individuals with varying amounts of belongings during their journeys.",
    "The smartphone's battery life extends between 10 and 12 hours, ensuring prolonged usage without the constant need for recharging, thereby catering to the diverse needs of users throughout the day.",
    "The oven's temperature settings offer a broad spectrum, allowing users to set it anywhere from 200 to 450 degrees Fahrenheit, facilitating the preparation of an extensive array of culinary delights with precision and finesse.",
    "The television boasts an expansive screen size starting at a minimum of 40 inches and extending beyond, delivering an immersive visual experience that captivates viewers with cinematic grandeur.",
    "Heart rate monitored by the fitness tracker surpasses 60 beats per minute while remaining beneath the upper limit of 160 beats per minute, ensuring accuracy in tracking diverse levels of physical exertion.",
    "The car's fuel efficiency exists within the range of 25 to 30 miles per gallon, symbolizing a harmonious relationship between economical fuel consumption and sustained travel distances, catering to environmentally conscious drivers.",
    "The digital camera's adaptive ISO sensitivity spans from a low setting of 100 to a high setting of 1600, enabling photographers to capture stunning images in various lighting conditions with exceptional clarity and detail.",
    "The extensive hiking trail stretches a considerable distance of 5 miles to beyond 10 miles, offering a range of experiences for those seeking both leisurely strolls and more challenging, adventurous treks through nature's scenic wonders.",
    "The refrigerator's adjustable temperature settings, modifiable between 1 and 8 degrees Celsius, afford users the ability to tailor the chilling environment to the specific requirements of different food items, preserving freshness effectively.",
    "The laptop's cutting-edge screen resolution, boasting levels above the standard 1080p, guarantees a visual feast for users engaged in graphic design, video editing, and other high-resolution demanding tasks, offering unparalleled clarity and vibrancy.",
    "Versatility defines the printer's multifunctional capabilities, featuring a printing speed ranging from 20 to over 30 pages per minute, making it a versatile tool suitable for both home and office environments, ensuring efficiency in document processing.",
    "The guitar, with its price tag falling within the range of $500 to just below $1000, strikes a balance between quality craftsmanship and affordability, providing options for various budgets and musical aspirations.",
    "The coffee maker's brewing time spans between 3 and 5 minutes, catering to individuals with diverse schedules and preferences, ensuring a quick and delightful coffee experience without compromising on flavor extraction.",
    "The microwave's adjustable power output in the expansive range of 800 to beyond 1200 watts grants users the flexibility to choose between gentle reheating and rapid cooking, adapting to culinary preferences and the varying nature of food items.",
    "The washing machine's dynamic spin speed varies from 800 to over 1200 revolutions per minute, accommodating a wide range of fabric types, from delicate garments requiring gentle care to more robust materials in need of thorough cleaning.",
    "The bicycle's versatile gear options span from a low of 1 to over 21, providing riders with the ideal mechanical advantage for both leisurely rides and challenging ascents, enhancing the overall cycling experience.",
    "The car's weight is distributed within the range of 1500 to over 2000 kilograms, offering stability on the road while allowing for a diverse range of body styles and features to suit individual preferences.",
    "The smartphone's camera, equipped with a zoom capability ranging from 2x to over 5x, ensures flexibility in photographic composition and creative expression.",
    "The conference room accommodates anywhere from 30 to just below 50 people, fostering collaboration and communication among participants.",
    "The laptop's capacious storage capacity exceeds 256 gigabytes, accommodating the burgeoning data requirements of users engaged in content creation, gaming, and other storage-intensive activities.",
    "The smart thermostat's adaptive temperature control ranges from just above 15 to below 30 degrees Celsius, allowing users to create a customized and energy-efficient climate within their living spaces.",
    "Illuminating spaces with adjustable brightness levels, the flashlight's brightness level ranges from just above 50 to 200 lumens, offering users the flexibility to illuminate spaces with varying degrees of intensity, catering to specific lighting requirements.",
    "The swimming pool's depth extends from just above 5 to below 10 feet, accommodating swimmers of different skill levels and preferences.",
    "The digital scale's precision in measuring weights spans between 1 and just below 5 kilograms, making it a versatile tool for culinary endeavors and fitness tracking.",
    "The coffee mug's voluminous capacity holds a volume between 8 and just below 12 ounces, accommodating various preferences for coffee, tea, or hot cocoa.",
    "The kitchen timer's versatility offers durations between 1 and just below 60 minutes, enhancing culinary precision and efficiency.",
    "The car's turning radius extends from just above 4 to below 6 meters, making it well-suited for navigating through tight urban spaces and parking with ease.",
    "The desk chair's adjustable height ranges from just above 40 to below 50 inches, providing ergonomic comfort in diverse work or study settings.",
    "The electric kettle's temperature range for heating water spans between 150 and just below 212 degrees Fahrenheit, catering to diverse tastes and preferences.",
    "The drone's flight time lasts between 15 and just below 20 minutes, allowing users to capture aerial footage and explore surroundings.",
    "The blender's multiple speed settings range from just above 1 to 5, ensuring versatility in blending preferences.",
    "The watch's water resistance is suitable for depths between just above 30 and below 50 meters, accommodating water activities such as swimming and snorkeling.",
    "The bookshelf's adjustable shelves are spaced from just above 8 to below 12 inches apart, catering to various storage needs for books, decor, and other items.",
    "The thermostat's programmable temperature range extends from just above 18 to below 28 degrees Celsius, allowing users to set personalized temperature schedules and minimize energy consumption.",
    "The vacuum cleaner's noise level ranges between 60 and just below 70 decibels, minimizing disruption in household environments.",
    "The bicycle's seat height is adjustable from just above 30 to below 40 inches, promoting ergonomic comfort during cycling activities.",
    "The smartwatch's battery life ranges from just above 2 to below 5 days, catering to users with varying degrees of device dependency.",
    "The camera's aperture is adjustable between just above f/2.8 and below f/16, enabling the capture of stunning and nuanced images.",
    "The computer monitor's refresh rate ranges between 60 and just below 144 hertz, making it suitable for gaming and multimedia applications.",
    "The hiking boots' price falls within the range of just above $80 to below $120, providing consumers with options that cater to diverse budgetary constraints.",
    "The oven's timer is adjustable for durations between 1 and just below 120 minutes, ensuring optimal results in culinary endeavors.",
    "The sound system's frequency response ranges within just above 40Hz to below 200kHz, providing listeners with immersive and high-fidelity sound.",
    "The alarm clock's volume is adjustable from just above 30 to below 60 decibels, promoting a personalized and gentle morning routine.",
    "The tablet's screen size ranges between 7 and just below 12 inches, providing options for entertainment, productivity, and creative endeavors.",
    "The skateboard's length spans from just above 28 to below 34 inches, accommodating various skateboarding styles.",
    "The refrigerator's energ`y consumption falls within the range of just above 100 to below 200 kilowatt-hours per month, appealing to environmentally conscious consumers.",
    "The drone's maximum altitude is within the range of just above 100 to below 500 feet, ensuring responsible and enjoyable usage.",
    "The coffee grinder's grind settings range from just above fine to below coarse, ensuring versatility for coffee enthusiasts and their preferred brewing styles."
]

long_single = [
    "The meticulously engineered keyboard boasts a precise length of 45.2 centimeters, ensuring an optimal typing experience for users seeking efficiency and comfort.",
    "The ultrathin laptop, with a sleek profile, features a weight of precisely 1.34 kilograms, making it an ideal companion for on-the-go professionals and students.",
    "A cutting-edge smartphone camera, equipped with a sensor resolution of exactly 108 megapixels, empowers users to capture stunningly detailed and vibrant images.",
    "The luxury wristwatch, crafted with precision, displays the exact time with a mechanical movement accuracy of 2 seconds per day, exemplifying exquisite horological craftsmanship.",
    "In the realm of audio excellence, the premium headphones deliver an unparalleled frequency response, covering a range of precisely 5Hz to 40kHz for a rich and immersive listening experience.",
    "The spacious hard drive provides an expansive storage capacity of 2 terabytes, accommodating the diverse digital needs of content creators, professionals, and multimedia enthusiasts.",
    "The ergonomic office chair, designed for optimal comfort during extended work sessions, offers an adjustable height setting with an exact range of 18 to 22 inches.",
    "The scientific calculator, an indispensable tool for mathematicians and students alike, performs complex calculations with precision, displaying results with up to 10 decimal places.",
    "The state-of-the-art laser printer produces high-resolution prints with exacting detail, achieving a printing resolution of 1200 x 2400 dots per inch for professional-quality documents.",
    "The compact digital scale, essential for precise measurements in culinary endeavors, provides an accuracy of 0.1 grams, catering to the meticulous needs of chefs and home cooks.",
    "The sleek and modern LED desk lamp illuminates workspaces with adjustable brightness levels, offering luminosity ranging from 300 to 800 lumens for customizable lighting conditions.",
    "The digital thermometer, an essential tool in healthcare, measures body temperature with clinical accuracy, displaying results with precision down to the tenth of a degree Celsius.",
    "The high-performance graphics card, a cornerstone of gaming rigs, boasts a graphics processing unit (GPU) with a clock speed precisely set at 1800 megahertz for immersive gaming experiences.",
    "The professional-grade DSLR camera captures moments with exceptional clarity, featuring a lens aperture of f/1.8 for optimal light intake and precise depth-of-field control.",
    "The adjustable standing desk, designed for ergonomic workspaces, accommodates users of varying heights with an exact height range adjustment from 27 to 46 inches.",
    "The electric kettle, designed for tea enthusiasts, heats water with precision, reaching an exact temperature of 95 degrees Celsius for the perfect cup of green tea.",
    "The advanced GPS navigation system guides travelers with precision, providing coordinates accurate to within one meter for precise location tracking and route planning.",
    "The atmospheric pressure sensor, crucial for meteorological measurements, detects air pressure with exacting precision, measuring within the range of 950 to 1050 hPa.",
    "The top-tier graphics tablet, favored by digital artists, boasts a pen pressure sensitivity of 8192 levels, allowing for precise and nuanced control in artistic creations.",
    "The industrial-grade laser distance measurer, a staple in construction, accurately measures distances with laser precision, providing readings with an exactitude of 1.5 millimeters.",
    "The elegant pendant necklace features a precisely cut diamond with a carat weight of 0.75, radiating brilliance and sophistication in its exquisite design.",
    "The versatile power drill, a staple in DIY projects, operates at an exact speed of 1500 revolutions per minute (RPM), providing efficient and controlled drilling performance.",
    "The energy-efficient LED lightbulb illuminates spaces with a warm glow, consuming precisely 9 watts of power for environmentally conscious and cost-effective lighting solutions.",
    "The compact air purifier, essential for clean indoor air, effectively filters particles down to 0.3 microns with a high-efficiency particulate air (HEPA) filter, ensuring exacting filtration.",
    "The culinary precision scale, a must-have in baking, accurately measures ingredients with a maximum capacity of 5 kilograms and an exact graduation of 1 gram.",
    "The premium espresso machine, beloved by coffee connoisseurs, brews coffee with exacting temperature control, maintaining a precise brewing temperature of 200 degrees Fahrenheit.",
    "The scientific-grade spectrophotometer, employed in research laboratories, measures absorbance with high accuracy, providing precise readings at wavelengths ranging from 190 to 1100 nanometers.",
    "The adjustable dumbbell set, perfect for home workouts, allows users to lift weights with precision, adjusting in increments of 2.5 pounds for gradual strength progression.",
    "The medical-grade blood pressure monitor, crucial for healthcare monitoring, records blood pressure with exacting precision, displaying readings with an accuracy of +/- 2 mmHg.",
    "The ultra-responsive gaming mouse, designed for esports enthusiasts, features a customizable polling rate of 1000 Hz, ensuring exact and instantaneous cursor movements during gaming sessions.",
    "The minimalist wall clock, a stylish addition to any living space, keeps time with precision, featuring clock hands that move with exactness, ticking away the seconds and minutes.",
    "The sleek smart thermostat, enhancing home energy efficiency, maintains temperatures with precision, allowing users to set exact temperature thresholds within a range of 18 to 25 degrees Celsius.",
    "The advanced heart rate monitor, a vital tool for fitness enthusiasts, tracks heart rate with exacting accuracy, providing real-time readings with a margin of error of just 1 beat per minute.",
    "The professional-grade hairdryer, designed for salon-quality styling, operates with a motor speed of precisely 1800 watts, delivering powerful and precise airflow for efficient hair drying.",
    "The high-resolution computer monitor, favored by graphic designers, boasts a pixel density of 150 pixels per inch, displaying images and text with exquisite detail and clarity.",
    "The culinary sous vide immersion circulator, a favorite among chefs, maintains water temperature with precision, cooking food to perfection with an exact temperature control range of 45 to 85 degrees Celsius.",
    "The industrial-grade laser level, essential in construction projects, projects laser lines with precision, ensuring exact leveling and alignment with an accuracy of 1.5 millimeters at 5 meters.",
    "The ergonomic gaming chair, crafted for comfort during long gaming sessions, supports users with an exact weight capacity of 150 kilograms, providing durability and stability.",
    "The compact air compressor, a versatile tool in DIY projects, delivers compressed air with precision, featuring an exact maximum pressure output of 120 pounds per square inch (psi).",
    "The high-performance graphics processing unit (GPU), vital for graphic-intensive tasks, features a memory bandwidth of precisely 256 gigabytes per second, ensuring swift and efficient data processing.",
    "The elegant wristwatch, a symbol of timeless style, features a case diameter of exactly 40 millimeters, striking a perfect balance between classic aesthetics and contemporary design.",
    "The efficient robotic vacuum cleaner, a boon for automated cleaning, navigates spaces with precision, featuring sensors that detect obstacles with an accuracy of 98% in obstacle avoidance.",
    "The immersive virtual reality headset, a gateway to digital realms, offers an expansive field of view at exactly 110 degrees, providing users with a lifelike and captivating VR experience.",
    "The digital pressure gauge, essential in industrial settings, measures pressure with exacting precision, displaying readings with an accuracy of 0.1 percent of the full-scale range.",
    "The adjustable camera tripod, a staple for photographers, extends to a maximum height of precisely 60 inches, providing stability and flexibility for capturing the perfect shot.",
    "The compact and portable external hard drive, a storage solution for data on the go, offers a storage capacity of exactly 1 terabyte, accommodating diverse digital storage needs.",
    "The precision laser mouse, favored by designers and professionals, boasts a sensitivity of 1600 dots per inch (DPI), ensuring precise and accurate cursor movements for detailed tasks."
]

sentences = [
    "Embracing the art of mixology, a well-crafted cocktail may contain alcohol content within the range of 15% to 25%, offering a spectrum of flavors and intensities to satisfy diverse palates.",
    "In the realm of culinary mastery, chefs often recommend cooking poultry to an internal temperature ranging between 165 and 175 degrees Fahrenheit, ensuring both safety and succulence in every bite.",
    "Navigating the vast universe of digital photography, a high-quality camera sensor is capable of capturing images with a resolution ranging from 20 to 50 megapixels, delivering stunning visual detail and clarity.",
    "Guiding financial prudence, experts advise individuals to maintain an emergency fund equivalent to three to six months' worth of living expenses, serving as a financial safety net in times of unexpected challenges.",
    "Balancing fitness aspirations, health enthusiasts often target a daily step count ranging from 10,000 to 15,000 steps, promoting cardiovascular health and an active lifestyle.",
    "Harnessing the power of renewable energy, solar panels are designed to operate with an efficiency range of 15% to 22%, converting sunlight into electricity and contributing to sustainable power generation.",
    "Defining architectural marvels, skyscrapers can soar to heights ranging from 500 to 1,000 feet, symbolizing human ingenuity and pushing the boundaries of urban development.",
    "Sculpting the auditory landscape, a high-quality sound system can reproduce frequencies within the range of 20 to 20,000 Hertz, delivering a rich and immersive audio experience across the entire spectrum of human hearing.",
    "In the culinary domain, the recommended cooking time for a perfectly medium-rare steak falls within the range of 3 to 5 minutes per side, striking a delicate balance between tenderness and flavor.",
    "Balancing academic rigor, a standard undergraduate degree program typically requires completion of 120 to 150 credit hours, encompassing a diverse curriculum and ensuring a comprehensive education.",
    "Charting the ebbs and flows of financial markets, a moderate annual return on investment is often considered to be in the range of 5% to 8%, providing a benchmark for evaluating the performance of investment portfolios.",
    "Illuminating our surroundings, LED light bulbs are renowned for their energy efficiency, consuming power within the range of 6 to 10 watts, offering a greener alternative to traditional incandescent bulbs.",
    "Ensuring optimal hydration, health experts recommend daily water intake within the range of 8 to 10 cups, supporting bodily functions and promoting overall well-being.",
    "In the realm of celestial wonders, a telescope's aperture, or lens diameter, can vary between 80 and 120 millimeters, influencing the instrument's ability to capture and magnify distant cosmic phenomena.",
    "Guiding vehicular safety, tire pressure is advised to be maintained within the range of 30 to 35 pounds per square inch (psi), optimizing traction and fuel efficiency.",
    "Unveiling the intricacies of nutrition, dietary fiber intake is recommended to be within the range of 25 to 35 grams per day, supporting digestive health and overall nutritional balance.",
    "Showcasing the dynamic world of cinematic frame rates, movies are typically filmed and displayed at a standard rate of 24 frames per second, capturing motion with a cinematic and visually pleasing quality.",
    "Expanding the horizons of technological innovation, smartphones boast storage capacities ranging from 128 to 512 gigabytes, accommodating the growing demand for multimedia content and applications.",
    "In the realm of sustainable transportation, electric cars offer a driving range spanning from 200 to 400 miles on a single charge, reshaping the landscape of eco-friendly mobility.",
    "Crafting the perfect cup, coffee brewing experts often recommend water temperatures in the range of 195 to 205 degrees Fahrenheit, extracting flavors with precision and finesse.",
    "Defining the limits of atmospheric exploration, commercial airplanes cruise at altitudes ranging from 30,000 to 40,000 feet, navigating the skies with efficiency and safety.",
    "Embracing the digital frontier, internet speeds for residential broadband connections typically range from 50 to 100 megabits per second, enabling seamless online experiences.",
    "Anchoring the essence of timepieces, luxury watches may boast power reserves ranging from 40 to 80 hours, reflecting the craftsmanship and precision of their mechanical movements.",
    "Charting the course of global navigation, GPS accuracy is refined to within the range of 1 to 3 meters, providing precise location data for diverse applications.",
    "Sailing the seas of renewable energy, wind turbines generate electricity with capacities ranging from 2 to 8 megawatts, harnessing the power of the wind to contribute to sustainable power grids.",
    "Evoking the world of photographic composition, camera lenses often feature apertures with f-stop values ranging from f/1.4 to f/16, allowing photographers to control depth of field and light intake.",
    "Unveiling the realm of biodiversity, an acre of tropical rainforest may harbor anywhere from 100 to 300 species of trees, illustrating the richness and complexity of these vital ecosystems.",
    "Transforming the landscape of virtual reality, VR headsets offer field-of-view angles ranging from 90 to 120 degrees, immersing users in expansive and lifelike digital environments.",
    "Unraveling the mysteries of geological forces, earthquakes exhibit magnitudes within the range of 4 to 9 on the Richter scale, reflecting variations in intensity and potential impact.",
    "Bridging the realms of culinary creativity, the ideal oven temperature for baking artisan bread often falls within the range of 400 to 450 degrees Fahrenheit, ensuring the perfect balance of crust and crumb."
]


for sentence in sentences:

    sensors = list(text_parser.parse(sentence))

    print(f"Sentence {sentence}", f"Sensor {json.dumps(sensors, cls=CustomEncoder)}", sep='\n', end='\n\n')

