from spacy import Language

import spacy

from services.decorators.number_validation import validate_numbers_spacy

SPACY_MODEL = spacy.load("en_core_web_sm")
Language.__call__ = validate_numbers_spacy(Language.__call__)

# DEPENDENCIES
NEGATION_DEP = 'neg'
CONJUNCTION_DEP = 'cc'
ADVERBIAL_MODIFIER_DEP = 'advmod'
QUANTITY_MODIFIER_DEP = 'quantmod'

# POS TAGS
NUMERICAL_POS_TAG = "NUM"
ADVERB_POS_TAG = "ADV"
ADJECTIVE_POS_TAG = "ADJ"
ADPOSITION_POS_TAG = 'ADP'
VERB_POS_TAG = 'VERB'
NOUN_POS_TAG = 'NOUN'
COORDINATING_CONJUNCTION_POS_TAG = 'CCONJ'
CONJUNCTION_POS_TAG = 'CONJ'
SUBORDINATING_CONJUNCTION_POS_TAG = 'SCONJ'
PUNCTUATION_POS_TAG = 'PUNCT'
PARTICLE_POS_TAG = 'PART'
SYMBOL_POS_TAG = 'SYM'
PRONOUN_POS_TAG = 'PRON'

# ATTRIBUTES
SPACY_DEP_ATR = 'dep_'
SPACY_POS_ATR = 'pos_'

# PATTERNS
PATTERN_POS_ATTR = 'POS'
PATTERN_DEP_ATTR = 'DEP'
PATTERN_OP_ATTR = 'OP'
PATTERN_IN_ATTR = 'IN'
PATTERN_NOT_IN_ATTR = 'NOT_IN'
PATTERN_TEXT_ATTR = 'TEXT'
